# Generated by Django 2.1.1 on 2018-09-26 16:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_getingusersemails_registerd_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='getingusersemails',
            name='registerd_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2018, 9, 26, 16, 34, 35, 294402, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
